adding confirmOverride modal
cpinitiative/ide pull request #43
Opened 2021-10-28 13:44 UTC by sharad-sharma

Here I am using 3 atoms, one for storing error.credentials and 2 for handling modals. Idk any good way to store callback function to atom and to be able to call that on modal so, I have used these 3 atoms to do this task.

2021-10-29 21:30 UTC, thecodingwizard requested changes
The code still uses three atoms. I've left some comments detailing how to reduce it down to one atom. The logic for signing in should go in the `signInWithGoogleAtom`. Let me know if anything is unclear :)

2021-10-29 21:30 UTC, thecodingwizard commented on src/atoms/firebaseUserAtoms.ts
> +);
I don't think we need this atom. It's only used in one location

2021-10-29 21:30 UTC, thecodingwizard commented on src/atoms/firebaseUserAtoms.ts
> +)
These two should be combined into one atom. Also, the logic of signing in with credential should go in the `signInWithGoogle` atom, not in this atom. The show confirm modal atom should just accept a callback function; the logic for signing in should be in this callback function that's set by the `signInWithGoogle` atom

2021-10-29 21:30 UTC, thecodingwizard commented on src/atoms/firebaseUserAtoms.ts
> +          set(showConfirmModal, true);
Just set a singular atom here, passing in a callback for what happens when the user confirms data override. ie:

```
firebase.auth().signInWithCredential(error.credential);
```

2021-10-29 21:30 UTC, thecodingwizard commented on src/components/ConfirmOverrideModal.tsx
> +                setConfirmOverrideAtom(true);
call the callback function, then set the atom to nul

2021-10-29 21:30 UTC, thecodingwizard commented on src/components/ConfirmOverrideModal.tsx
> +                setConfirmOverrideAtom(false);
set the atom to null without calling the callback function

2021-11-09 22:55 UTC, thecodingwizard commented
@sharad-sharma any updates? :)

2021-11-10 10:57 UTC, sharad-sharma commented
@thecodingwizard 

I'm working on it. I will fix it soon.

2021-12-10 05:09 UTC, merged